name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile

jobs:
 
  Testing:
    env:
      PYTHONDEVMODE: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Download Ctbert
        run: |
          git clone https://huggingface.co/zTaoPlus/ctbert ckpt

      - name: Check Ckpt Exists
        run: |
          ls -la .