name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile

jobs:
  Testing:
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, windows-latest]
        install-via: [pip]
        arch: [x64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-ctbert
        with:
          path: downloads
          key: ci-model-cache-${{ hashFiles('CTBERTHASH') }}
          enableCrossOsArchive: true
      - name: Set up CUDA
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get install nvidia-cuda-toolkit
          sudo ldconfig
      - name: Run Python
        shell: bash
        run: ls ./downloads