name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Git Clone Ctbert From Huggingface
        run: |
          # mkdir -p /usr/local/src/downloads
          # cd /usr/local/src/downloads
          git clone https://huggingface.co/zTaoPlus/ctbert ckpt

  Testing:
    env:
      PYTHONDEVMODE: 1
    runs-on: ubuntu-latest
    needs: Download
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Ckpt Exists
        run: |
           ls -la .