name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - Dockerfile

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Cache Ctbert
        id: cache-ctbert
        uses: actions/cache@v3
        with:
          path: downloads
          key: ci-model-cache-${{ hashFiles('CTBERTHASH') }}
          restore-keys: |
            ci-model-cache-
          enableCrossOsArchive: true

      # Both have ctbert and bert files
      - name: Download Ctbert From HuggingFace
        if: steps.cache-ctbert.outputs.cache-hit != 'true'
        run: |
          mkdir -p downloads
          cd downloads
          git clone https://huggingface.co/zTaoPlus/ctbert ckpt
          cd ckpt
          rm -rf .git
  
  Testing:
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}
    needs: [Download]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, windows-latest]
        install-via: [pip]
        arch: [x64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-ctbert
        with:
          path: downloads
          key: ci-model-cache-${{ hashFiles('CTBERTHASH') }}
          enableCrossOsArchive: true
      - name: Run Python
        shell: bash
        run: ls ./downloads